### ISSUE TITLE
Problem adding picture to Wiki

### ISSUE THREAD

**Issue by seaniemc** [sarbjeetkumar/GoProject#14]
I was trying to add a picture to the Wiki, But the url I gave from Google Drive will not will not display.

**Comment by jasonthorne** [comment]
Found solution [here](http://solutionoptimist.com/2013/12/28/awesome-github-tricks/)

Added test image to README as example.

**Comment by seaniemc** [comment]
![develoment life cycle](https://cloud.githubusercontent.com/assets/9398358/20218545/0d0d8c42-a81d-11e6-9f9f-27a2f275b224.jpg)
Thanks Jason thats great.
