### ISSUE TITLE
Architecture model

### ISSUE THREAD

**Issue by seaniemc** [sarbjeetkumar/GoProject#2]
Research and create a visual representation of the Architecture model

**Comment by sarbjeetkumar** [comment]
#Technologies  For front end , Middle ware and Back End.

###**Front end**

- Bootstrap
[http://getbootstrap.com/](url)

- AngularJS
[https://angularjs.org/](url)

- JQuery
[https://jquery.com/](url)


### Middle Ware (API)

Must be written in Go 

[https://golang.org/](url)


-###Backend(Database)

- I think we all agreed to use MongoDB

[https://www.mongodb.com/](url) 


###Frameworks

- Gorilla
[http://www.gorillatoolkit.org/](url)

- Macaron
[https://go-macaron.com/docs](url)

#####If i am missing anything please add in .

**Comment by seaniemc** [comment]
Seems perfect
