### ISSUE TITLE
Initial Pop up seems to disable all the routing.

### ISSUE THREAD

**Issue by seaniemc** [sarbjeetkumar/GoProject#23]
Hey Jason. When i navigated to the site for the first time, the pop up seems to disable all the routing. If I close the browser and open it again. The routing is working again. Can you have a look and see if know what the problem is. Thanks Sean.

**Comment by jasonthorne** [comment]
There seems to have been changes made to my code from line 92 to 103. That may be the problem, as I'm unsure why they're there. For example, the SHA from my last commit on that page is typed on line 103. Maybe its something to do with pulls from differing branches?  I'll look into it anyway, and I'll be around tomorrow to meet up. Also, what browser were you using, so I can try replicate the problem?

**Comment by seaniemc** [comment]
Hey Jason. I was using chrome browser, I think it was it was adding elements like <<< and some sort of Hash code to the app.js and the index.html

**Comment by seaniemc** [comment]
Hey Jason. We had conflicts when merging and had to revert to a previous state. Model is not in any of the branches but you can sort it out tomorrow.

**Comment by jasonthorne** [comment]
Added now.
